apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-metadata
spec:
  playbook: osp.edpm.neutron_metadata
  dataSources:
    - secretRef:
        name: neutron-ovn-metadata-agent-neutron-config
    - secretRef:
        name: nova-metadata-neutron-config
  tlsCerts:
    default:
      contents:
      - dnsnames
      - ips
      networks:
      - ctlplane
      issuer: osp-rootca-issuer-ovn
      keyUsages:
        - digital signature
        - key encipherment
        - client auth
  caCerts: combined-ca-bundle
  containerImageFields:
  - EdpmNeutronMetadataAgentImage
  edpmServiceType: neutron-metadata
