apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: telemetry-power-monitoring
spec:
  dataSources:
    - secretRef:
        name: ceilometer-compute-config-data
  playbook: osp.edpm.telemetry_power_monitoring
  tlsCerts:
    default:
      contents:
      - ips
      - dnsnames
  caCerts: combined-ca-bundle
  containerImageFields:
  - CeilometerIpmiImage
  - EdpmKeplerImage
