apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: libvirt
spec:
  playbook: osp.edpm.libvirt
  secrets:
    # NOTE: this Secret needs to be created before deploying the data plane.
    # It should contain the libvirt sasl auth password using the key LibvirtPassword
    - libvirt-secret
  tlsCerts:
    default:
      contents:
        - dnsnames
        - ips
      networks:
        - ctlplane
      keyUsages:
        - digital signature
        - key encipherment
        - server auth
        - client auth
      issuer: osp-rootca-issuer-libvirt
  caCerts: combined-ca-bundle
