apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: frr
spec:
  playbook: osp.edpm.frr
  dependsOn:
    - run-os
    - validate-network
  containerImageFields:
  - EdpmFrrImage
  edpmServiceType: frr
