apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: ovn-bgp-agent
spec:
  playbook: osp.edpm.ovn_bgp_agent
  dataSources:
    - secretRef:
        name: neutron-ovn-agent-neutron-config
    - configMapRef:
        name: ovn-bgp-agent-extra-config
        optional: true
  tlsCerts:
    rbac:
      commonName: system-id
      issuer: osp-rootca-issuer-ovn
      keyUsages:
        - digital signature
        - client auth
  caCerts: combined-ca-bundle
  containerImageFields:
  - EdpmOvnBgpAgentImage
  edpmServiceType: ovn-bgp-agent
