apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: swift
spec:
  playbook: osp.edpm.swift
  dependsOn:
    - run-os
    - validate-network
  dataSources:
    - secretRef:
        name: swift-conf
    - configMapRef:
        name: swift-storage-config-data
    - configMapRef:
        name: swift-ring-files
  containerImageFields:
  - SwiftAccountImage
  - SwiftContainerImage
  - SwiftObjectImage
  - SwiftProxyImage
  edpmServiceType: swift
