# This patch inject custom ENV settings to the manager container
# Used to set our default image locations
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-operator-controller-init
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: RELATED_IMAGE_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-k8s-operators/openstack-baremetal-operator-agent:latest
        - name: RELATED_IMAGE_ANSIBLEEE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
        - name: RELATED_IMAGE_AODH_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-aodh-api:master-latest
        - name: RELATED_IMAGE_AODH_EVALUATOR_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-aodh-api:master-latest
        - name: RELATED_IMAGE_AODH_LISTENER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-aodh-api:master-latest
        - name: RELATED_IMAGE_AODH_NOTIFIER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-aodh-api:master-latest
        - name: RELATED_IMAGE_APACHE_IMAGE_URL_DEFAULT
          value: registry.redhat.io/ubi9/httpd-24:latest
        - name: RELATED_IMAGE_BARBICAN_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-barbican-api:master-latest
        - name: RELATED_IMAGE_BARBICAN_KEYSTONE_LISTENER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-barbican-api:master-latest
        - name: RELATED_IMAGE_BARBICAN_WORKER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-barbican-api:master-latest
        - name: RELATED_IMAGE_CEILOMETER_CENTRAL_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ceilometer-central:master-latest
        - name: RELATED_IMAGE_CEILOMETER_COMPUTE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ceilometer-compute:master-latest
        - name: RELATED_IMAGE_CEILOMETER_IPMI_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ceilometer-compute:master-latest
        - name: RELATED_IMAGE_CEILOMETER_NOTIFICATION_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ceilometer-central:master-latest
        - name: RELATED_IMAGE_CEILOMETER_MYSQLD_EXPORTER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-k8s-operators/mysqld_exporter:latest
        - name: RELATED_IMAGE_CEILOMETER_SGCORE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-k8s-operators/sg-core:latest
        - name: RELATED_IMAGE_KSM_IMAGE_URL_DEFAULT
          value: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0
        - name: RELATED_IMAGE_CINDER_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-cinder-api:master-latest
        - name: RELATED_IMAGE_CINDER_BACKUP_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-cinder-backup:master-latest
        - name: RELATED_IMAGE_CINDER_SCHEDULER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-cinder-scheduler:master-latest
        - name: RELATED_IMAGE_CINDER_VOLUME_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-cinder-volume:master-latest
        - name: RELATED_IMAGE_CLOUDKITTY_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-cloudkitty-api:master-latest
        - name: RELATED_IMAGE_CLOUDKITTY_PROC_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-cloudkitty-api:master-latest
        - name: RELATED_IMAGE_DESIGNATE_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-designate-api:master-latest
        - name: RELATED_IMAGE_DESIGNATE_BACKENDBIND9_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-designate-backend-bind9:master-latest
        - name: RELATED_IMAGE_DESIGNATE_CENTRAL_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-designate-central:master-latest
        - name: RELATED_IMAGE_DESIGNATE_MDNS_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-designate-central:master-latest
        - name: RELATED_IMAGE_DESIGNATE_PRODUCER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-designate-central:master-latest
        - name: RELATED_IMAGE_DESIGNATE_UNBOUND_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-unbound:master-latest
        - name: RELATED_IMAGE_DESIGNATE_WORKER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-designate-worker:master-latest
        - name: RELATED_IMAGE_EDPM_FRR_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-frr:master-latest
        - name: RELATED_IMAGE_EDPM_LOGROTATE_CROND_IMAGE_URL_DEFAULT
          value: quay.io/podified-antelope-centos9/openstack-cron:current-podified
        - name: RELATED_IMAGE_EDPM_NEUTRON_DHCP_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-neutron-dhcp-agent:master-latest
        - name: RELATED_IMAGE_EDPM_NEUTRON_METADATA_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-neutron-metadata-agent-ovn:master-latest
        - name: RELATED_IMAGE_EDPM_NEUTRON_OVN_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-neutron-ovn-agent:master-latest
        - name: RELATED_IMAGE_EDPM_NEUTRON_SRIOV_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-neutron-sriov-agent:master-latest
        - name: RELATED_IMAGE_EDPM_NODE_EXPORTER_IMAGE_URL_DEFAULT
          value: quay.io/prometheus/node-exporter:v1.5.0
        - name: RELATED_IMAGE_EDPM_KEPLER_IMAGE_URL_DEFAULT
          value: quay.io/sustainable_computing_io/kepler:release-0.7.12
        - name: RELATED_IMAGE_OPENSTACK_NETWORK_EXPORTER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-k8s-operators/openstack-network-exporter:current-podified
        - name: RELATED_IMAGE_EDPM_OVN_BGP_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/podified-antelope-centos9/openstack-ovn-bgp-agent:current-podified
        - name: RELATED_IMAGE_EDPM_PODMAN_EXPORTER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-k8s-operators/prometheus-podman-exporter:latest
        - name: RELATED_IMAGE_GLANCE_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-glance-api:master-latest
        - name: RELATED_IMAGE_HEAT_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-heat-api:master-latest
        - name: RELATED_IMAGE_HEAT_CFNAPI_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-heat-api:master-latest
        - name: RELATED_IMAGE_HEAT_ENGINE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-heat-engine:master-latest
        - name: RELATED_IMAGE_HORIZON_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-horizon:master-latest
        - name: RELATED_IMAGE_INFRA_MEMCACHED_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-memcached:master-latest
        - name: RELATED_IMAGE_INFRA_REDIS_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-redis:master-latest
        - name: RELATED_IMAGE_IRONIC_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ironic-api:master-latest
        - name: RELATED_IMAGE_IRONIC_CONDUCTOR_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ironic-conductor:master-latest
        - name: RELATED_IMAGE_IRONIC_INSPECTOR_IMAGE_URL_DEFAULT
          value: quay.io/podified-antelope-centos9/openstack-ironic-inspector:current-podified
        - name: RELATED_IMAGE_IRONIC_NEUTRON_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ironic-neutron-agent:master-latest
        - name: RELATED_IMAGE_IRONIC_PXE_IMAGE_URL_DEFAULT
          value: quay.io/podified-antelope-centos9/openstack-ironic-pxe:current-podified
        - name: RELATED_IMAGE_IRONIC_PYTHON_AGENT_IMAGE_URL_DEFAULT
          value: quay.io/podified-antelope-centos9/ironic-python-agent:current-podified
        - name: RELATED_IMAGE_KEYSTONE_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-keystone:master-latest
        - name: RELATED_IMAGE_MANILA_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-manila-api:master-latest
        - name: RELATED_IMAGE_MANILA_SCHEDULER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-manila-scheduler:master-latest
        - name: RELATED_IMAGE_MANILA_SHARE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-manila-share:master-latest
        - name: RELATED_IMAGE_MARIADB_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-mariadb:master-latest
        - name: RELATED_IMAGE_NET_UTILS_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-netutils:master-latest
        - name: RELATED_IMAGE_NEUTRON_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-neutron-server:master-latest
        - name: RELATED_IMAGE_NOVA_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-nova-api:master-latest
        - name: RELATED_IMAGE_NOVA_COMPUTE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-nova-compute:master-latest
        - name: RELATED_IMAGE_NOVA_CONDUCTOR_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-nova-conductor:master-latest
        - name: RELATED_IMAGE_NOVA_NOVNC_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-nova-novncproxy:master-latest
        - name: RELATED_IMAGE_NOVA_SCHEDULER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-nova-scheduler:master-latest
        - name: RELATED_IMAGE_OCTAVIA_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-octavia-api:master-latest
        - name: RELATED_IMAGE_OCTAVIA_HEALTHMANAGER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-octavia-worker:master-latest
        - name: RELATED_IMAGE_OCTAVIA_HOUSEKEEPING_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-octavia-worker:master-latest
        - name: RELATED_IMAGE_OCTAVIA_WORKER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-octavia-worker:master-latest
        - name: RELATED_IMAGE_OCTAVIA_RSYSLOG_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-rsyslog:master-latest
        - name: RELATED_IMAGE_OPENSTACK_CLIENT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-openstackclient:master-latest
        - name: RELATED_IMAGE_OS_CONTAINER_IMAGE_URL_DEFAULT
          value: quay.io/podified-antelope-centos9/edpm-hardened-uefi:current-podified
        - name: RELATED_IMAGE_OVN_CONTROLLER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ovn-controller:master-latest
        - name: RELATED_IMAGE_OVN_CONTROLLER_OVS_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ovn-base:master-latest
        - name: RELATED_IMAGE_OVN_NB_DBCLUSTER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ovn-nb-db-server:master-latest
        - name: RELATED_IMAGE_OVN_NORTHD_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ovn-northd:master-latest
        - name: RELATED_IMAGE_OVN_SB_DBCLUSTER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ovn-sb-db-server:master-latest
        - name: RELATED_IMAGE_PLACEMENT_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-placement-api:master-latest
        - name: RELATED_IMAGE_RABBITMQ_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-rabbitmq:master-latest
        - name: RELATED_IMAGE_SWIFT_ACCOUNT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-swift-account:master-latest
        - name: RELATED_IMAGE_SWIFT_CONTAINER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-swift-container:master-latest
        - name: RELATED_IMAGE_SWIFT_OBJECT_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-swift-object:master-latest
        - name: RELATED_IMAGE_SWIFT_PROXY_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-swift-proxy-server:master-latest
        - name: RELATED_IMAGE_TEST_TEMPEST_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-tempest:master-latest
        - name: RELATED_IMAGE_WATCHER_API_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-watcher-base:master-latest
        - name: RELATED_IMAGE_WATCHER_APPLIER_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-watcher-base:master-latest
        - name: RELATED_IMAGE_WATCHER_DECISION_ENGINE_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-watcher-base:master-latest
          # NOTE: TEST_ images below do not get released downstream. They should not be prefixed with RELATED
        - name: TEST_TOBIKO_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-tobiko:master-latest
        - name: TEST_ANSIBLETEST_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-ansible-test:master-latest
        - name: TEST_HORIZONTEST_IMAGE_URL_DEFAULT
          value: quay.io/openstack-s2i-containers/openstack-horizontest:master-latest
        - name: RELATED_IMAGE_OPENSTACK_MUST_GATHER_DEFAULT
          value: quay.io/openstack-k8s-operators/openstack-must-gather:latest
