[id="con_provisioning-bare-metal-data-plane-nodes_{context}"]
= Provisioning bare metal data plane nodes

[role="_abstract"]
Provisioning bare metal nodes on the data plane is supported with the Red Hat OpenShift
Container Platform (RHOCP) Cluster Baremetal Operator (CBO). The CBO is a RHOCP Operator
responsible for deploying all the components that are required to provision bare metal
nodes within the RHOCP cluster, including the Bare Metal Operator (BMO) and Ironic
containers.

== Installer-Provisioned Infrastructure

CBO is enabled by default on RHOCP clusters that are installed with the baremetal
installer-provisioned infrastructure. You can configure installer-provisioned clusters
with a provisioning network to enable both virtual media and network boot installations.
You can alternatively configure an installer-provisioned cluster without a provisioning
network so that only virtual media provisioning is possible.

== Assisted Installer Provisioned Infrastructure

You can enable CBO on clusters installed with the Assisted Installer, and you can manually
add the provisioning network to the Assisted Installer cluster after installation.

== User Provisioned Infrastructure

You can activate CBO on RHOCP clusters installed with user-provisioned infrastructure by
creating a Provisioning CR. You cannot add a provisioning network to a user-provisioned
cluster.

For user-provisioned insfrastructure a provisioning CR has to be created manually as below:

 apiVersion: metal3.io/v1alpha1
 kind: Provisioning
 metadata:
   name: provisioning-configuration
 spec:
   provisioningNetwork: "Disabled"
   watchAllNamespaces: false

BMO manages the available hosts on clusters and performs the following operations:

* Inspects node hardware details and reports them to the corresponding BareMetalHost CR.
This includes information about CPUs, RAM, disks and NICs.
* Provisions nodes with a specific image.
* Cleans node disk contents before and after provisioning.

== Provisioning Nodes with OpenStackDataPlaneNodeSet

Before deploying dataplane nodes on baremetal, ensure that CBO has been enabled/activated
with clusters installed with the different installers mentioned above.

Sufficient number of edpm node BareMetalHost(BMH) CRs should be created and be in
`Available` state (after inspection).By default baremetal-operator would be looking
for BMHs in the `openshift-machine-api` namespace.

`Provisioning` resource should be patched to watch all namespaces with `watchAllNamespaces: true`
as the secrets would be created in `openstack` namespace, in spite of BMHs in `openshift-machine-api`
namespace.

[,console]
----
$ oc patch provisioning provisioning-configuration --type merge -p '{"spec":{"watchAllNamespaces": true }}'
----

Sample BMH spec:

 apiVersion: metal3.io/v1alpha1
 kind: BareMetalHost
 metadata:
   name: edpm-compute-01
   namespace: openstack
   labels:
     app: openstack
     workload: compute
 spec:
   bmc:
     address: redfish+http://192.168.111.1:8000/redfish/v1/Systems/e8efd888-f844-4fe0-9e2e-498f4ab7806d
     credentialsName: node-bmc-secret
   bootMACAddress: 00:c7:e4:a7:e7:f3
   bootMode: UEFI
   online: false

BMH `labels` should be set appropriately for the desired nodes so that it can be used
by the `bmhLabelSelector` in the `OpenStackDataPlaneNodeSet` spec.

For virtual-media provisioning BMC address should use virtual-media as below.

 bmc:
   address: redfish-virtualmedia+http://192.168.111.1:8000/redfish/v1/Systems/e8efd888-f844-4fe0-9e2e-498f4ab7806d

To provision the baremetal nodes for edpm, OpenStackDataPlaneNodeSet spec should have the
`baremetalSetTemplate` section as show below. Other than `bmhLabelSelector`, `hardwareReqs`
field can also be provided for appropriate BMH selection. To select a particular BMH for a
node, `bmhLabelSelector` can be provided in the node section of the `OpenStackDataPlaneNodeSet`
spec. These labels would be used in addition to the labels set in `baremetalSetTemplate` to
select BMHs for the node.

 apiVersion: dataplane.openstack.org/v1beta1
 kind: OpenStackDataPlaneNodeSet
 metadata:
   name: openstack-edpm
 spec:
   baremetalSetTemplate:
     bmhLabelSelector:
       app: openstack
       workload: compute
     ctlplaneInterface: enp1s0
     cloudUserName: cloud-admin
   nodes:
     edpm-compute-0
       hostName: edpm-compute-0
       ansible:
         ansibleHost: 192.168.122.100
       bmhLabelSelector:
         nodeName: edpm-compute-01

== Configuring Network Interface Bonding for Control Plane

Network interface bonding (also known as NIC teaming) can be configured for the control plane
network to provide redundancy and increased throughput. The bonding configuration is specified
in the `baremetalSetTemplate` section using the `ctlplaneBond` field.

The bonding configuration includes:

* `bondInterfaces` - List of physical interfaces to bond (minimum 2 interfaces required)
* `bondMode` - Bonding mode to use (default: "active-backup")
* `bondOptions` - Additional bonding options as key-value pairs

Supported bonding modes include:

* `active-backup` - Only one interface is active at a time for fault tolerance
* `802.3ad` - IEEE 802.3ad Dynamic link aggregation (LACP)
* `balance-rr` - Round-robin policy for load balancing
* `balance-xor` - XOR policy for load balancing
* Other modes supported by cloud-init

Example configuration with bonding:

 apiVersion: dataplane.openstack.org/v1beta1
 kind: OpenStackDataPlaneNodeSet
 metadata:
   name: openstack-edpm
 spec:
   baremetalSetTemplate:
     bmhLabelSelector:
       app: openstack
       workload: compute
     ctlplaneInterface: bond0
     ctlplaneBond:
       bondInterfaces:
         - eno1
         - eno2
       bondMode: "802.3ad"
       bondOptions:
         bond-miimon: "100"
         bond-xmit-hash-policy: "layer3+4"
     cloudUserName: cloud-admin
   nodes:
     edpm-compute-0:
       hostName: edpm-compute-0

When bonding is configured, the `ctlplaneInterface` should be set to the bond interface name
(e.g., `bond0`), and the physical interfaces specified in `bondInterfaces` will be configured
as members of the bond during node provisioning.

=== Relevant Status Condition

`NodeSetBaremetalProvisionReady` condition in status condtions reflects the status of
baremetal provisioning as shown below.

[,console]
----
$ oc get openstackdataplanenodeset openstack-edpm-ipam -o json | jq '.status.conditions[] | select(.type=="NodeSetBaremetalProvisionReady")'
{
  "lastTransitionTime": "2024-02-01T04:41:58Z",
  "message": "NodeSetBaremetalProvisionReady ready",
  "reason": "Ready",
  "status": "True",
  "type": "NodeSetBaremetalProvisionReady"
}
----
