= Composable services

Composable services with openstack-operator provide a way for users to
customize services that are deployed on dataplane nodes. It is possible to
"compose" a set of services such that the dataplane deployment can be
customized in whichever ways are needed.

Composing services can take different forms. The interfaces in
openstack-operator allow for:

* Enabling/disabling services
* Ordering services
* Developing custom services

For the purposes of the interfaces in openstack-operator, a service is an
ansible execution that manages a software deployment (installation,
configuration, execution, etc) on dataplane nodes. The ansible content that
makes up each service is defined by the service itself. Each service is a
resource instance of the
xref:openstack_dataplaneservice.adoc[`OpenStackDataPlaneService`] CRD.

== openstack-operator provided services

openstack-operator provides a default list of services that will be deployed on
dataplane nodes. The services list is set on the
<<openstackdataplanenodesetspec,OpenStackDataPlaneNodeSet>> CRD.

The default list of services as they will appear on the `services` field on an
`OpenStackDataPlaneNodeSet` spec is:

----
services:
  - redhat
  - download-cache
  - bootstrap
  - configure-network
  - validate-network
  - install-os
  - configure-os
  - run-os
  - libvirt
  - nova
  - ovn
  - neutron-metadata
  - telemetry
----

If the `services` field is omitted from the `OpenStackDataPlaneNodeSet` spec,
then the above list will be used.

The associated `OpenStackDataPlaneService` resources are reconciled during
`OpenStackDataPlaneNodeSet` reconciliation if the service is in the NodeSets'
service list.

The DataPlane Operator also includes the following services that are not enabled by default:

[cols="40%a,60%a",options="header",]
|===
|Service |Description
|`ceph-client` |Include this service to configure data plane nodes as clients of a Red Hat Ceph Storage server. Include between the `install-os` and `configure-os` services. The `OpenStackDataPlaneNodeSet` CR must include the following configuration to access the Red Hat Ceph Storage secrets:

----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
spec:
  ...
  nodeTemplate:
    extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        secret:
          secretName: ceph-conf-files
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true
----

|`ceph-hci-pre` |Include this service to prepare data plane nodes to host Red Hat Ceph Storage in an HCI configuration. For more information, see xref:assembly_configuring-a-hyperconverged-infrastructure-environment[Configuring a Hyperconverged Infrastructure environment].
|`configure-ovs-dpdk` |Include this service to configure OvS DPDK configuration on EDPM nodes. This service is needed to enable OvS DPDK on the compute nodes.
|`neutron-sriov` |Include this service to run a Neutron SR-IOV NIC agent on the data plane nodes.
|`neutron-metadata` |Include this service to run the Neutron OVN Metadata agent on the data plane nodes. This agent is required to provide metadata services to the Compute nodes.
|`neutron-ovn` |Include this service to run the Neutron OVN agent on the data plane nodes. This agent is required to provide QoS to hardware offloaded ports on the Compute nodes.
|`neutron-dhcp` |Include this service to run a Neutron DHCP agent on the data plane nodes.
|`cleanup` |Include this service to clean up containers and configurations for services that have been removed from the nodeset. The cleanup service compares the current services list with previously deployed services, removes containers for services no longer in the list, removes startup_config and configuration files, and runs service-specific cleanup tasks. Use this service via `servicesOverride` for one-time cleanup after removing services from a nodeset, or add to the services list if cleanup should run on every deployment.
|===

For more information about the available default services, see https://github.com/openstack-k8s-operators/openstack-operator/tree/main/config/services.

You can enable and disable services for an `OpenStackDataPlaneNodeSet` resource.

[NOTE]
Do not change the order of the default service deployments.

You can use the `OpenStackDataPlaneService` CRD to create custom services that you can deploy on your data plane nodes. You add your custom services to the default list of services where the service must be executed. For more information, see xref:proc_creating-a-custom-service_dataplane[Creating a custom service].

You can view the details of a service by viewing the YAML representation of the resource:

----
$ oc get openstackdataplaneservice configure-network -o yaml
----

== Overriding services for the deployment

The list of services that will be deployed when an
`OpenStackDataPlaneDeployment` is created is set on each
`OpenStackDataPlaneNodeSet` that is included in the `nodeSets` list on the
`OpenStackDataPlaneDeployment`.

This allows for deploying a different set of services on different
`OpenStackDataPlaneNodeSets` using the same `OpenStackDataPlaneDeployment`
resource simultaneously. It also maintains the association between services and
nodeSets on the nodeSet itself. This association is important when nodeSets are
used to group nodes with hardware and configuration differences that require
the need for deploying different services on different nodeSets.

In some specific cases, it may be needed to override what services are deployed
on all nodeSets included in an `OpenStackDataPlaneDeployment`. These cases can
vary, but are often related to day 2 workflows such as update, upgrade, and
scale out. In these cases, it may be needed to execute a smaller subset of
services, or just a single service, across all nodeSets in the
`OpenStackDataPlaneDeployment`.

The `servicesOverride` field on `OpenStackDataPlaneDeployment` allow for this
behavior. Setting this field changes what services are deployed when the
`OpenStackDataPlaneDeployment` is created. If the field is set, only the
services listed in the field will be deployed on all nodeSets.

If deployment has been configured with `tlsEnabled` set to `True` in the
original `OpenStackDataPlaneNodeSet` CR, it is recommended to add also
`install-certs` to the list of services in `servicesOverride` list. That will
install certificates potentially required by the other services in
the destination nodes.

The following example `OpenStackDataPlaneDeployment` resource illustrates using
`servicesOverride` to perform a pre-upgrade task of executing just the ovn
service.

....
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-edpm-pre-upgrade-ovn
spec:

  nodeSets:
    - openstack-edpm

  // Only the services here will be executed. Overriding any services value
  // on the openstack-edpm nodeSet.
  // Service install-certs is added here to install certificates
  // potentially required by the ovn service
  servicesOverride:
    - install-certs
    - ovn
....

=== Cleaning up removed services

When services are removed from a nodeset's services list, their containers and
configuration files remain on the data plane nodes. Use the `cleanup` service
to remove these artifacts.

The cleanup service tracks which services were previously deployed on each node.
When executed, it identifies services that are no longer in the nodeset's
services list and removes their:

* Containers
* Startup configuration files
* Other configuration files
* Service-specific artifacts (via cleanup tasks defined in each role)

To enable cleanup of orphaned containers, set the `edpm_cleanup_orphaned_containers`
Ansible variable to `true` using `ansibleExtraVars` on the deployment.

The following example shows how to run a one-time cleanup after removing
services from a nodeset:

....
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-edpm-cleanup
spec:
  nodeSets:
    - openstack-edpm
  ansibleExtraVars:
    edpm_cleanup_orphaned_containers: true
  servicesOverride:
    - cleanup
....
