= Interacting with Ansible

When a dataplane service is executed during a role deployment, a corresponding
https://openstack-k8s-operators.github.io/openstack-ansibleee-operator/openstack_ansibleee/[OpenStackAnsibleEE]
resource is created. The OpenStackAnsibleEE resource is the associated ansible
execution with the service.

OpenStackAnsibleEE resources are reconciled by
https://github.com/openstack-k8s-operators/openstack-ansibleee-operator[openstack-ansibleee-operator].
During reconciliation a
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/[Job]
resource is created which in turn creates a
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/[Pod] resource. The pod is started with an https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html[Ansible Execution Environment] image, and runs https://ansible.readthedocs.io/projects/runner/en/stable/[ansible-runner].

== Retrieving and inspecting OpenStackAnsibleEE resources

During (or after) a deployment the instances of OpenStackAnsibleEE can be
retrieved from the API.

 oc get openstackansibleee

Sample output when the default list of services:

 NAME                                                  NETWORKATTACHMENTS   STATUS   MESSAGE
 configure-network-edpm-compute                        True     Job completed
 configure-os-edpm-compute                             True     Job completed
 install-os-edpm-compute                               True     Job completed
 libvirt-edpm-compute                                  True     Job completed
 nova-edpm-compute                                     True     Job completed
 run-os-edpm-compute                                   True     Job completed
 telemetry-edpm-compute                                True     Job completed
 validate-network-edpm-compute                         True     Job completed

Querying for pods with the OpenStackAnsibleEE label

 oc get pods -l app=openstackansibleee

Sample output:

 configure-network-edpm-compute-j6r4l   0/1     Completed           0          3m36s
 validate-network-edpm-compute-6g7n9    0/1     Pending             0          0s
 validate-network-edpm-compute-6g7n9    0/1     ContainerCreating   0          11s
 validate-network-edpm-compute-6g7n9    1/1     Running             0          13s

Querying for jobs, shows the corresponding job for each OpenStackAnsibleEE resource:

 oc get jobs -l app=openstackansibleee

Sample output:

 NAME                             COMPLETIONS   DURATION   AGE
 configure-network-edpm-compute   1/1           8s         2m51s
 configure-os-edpm-compute        1/1           8s         2m27s
 install-os-edpm-compute          1/1           8s         2m35s
 libvirt-edpm-compute             1/1           8s         2m35s
 nova-edpm-compute                1/1           8s         2m35s
 run-os-edpm-compute              1/1           8s         2m19s
 telemetry-edpm-compute           1/1           8s         2m35s
 validate-network-edpm-compute    1/1           8s         2m43s

Using the job name, the corresponding pod can be retrieved:

 oc get pods | grep configure-network-edpm-compute

Sample output:

 configure-network-edpm-compute-2hshp   0/1     Completed            0                5m45s

Using the job name, the ansible logs can be retrieved:

 oc logs job.batch/configure-network-edpm-compute

== Controlling the Ansible execution

For specifying the
ansible https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#selecting-or-skipping-tags-when-you-run-a-playbook[tags, skip-tags],
and https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html#patterns-and-ad-hoc-commands[limit]

The fields in OpenStackDataPlaneDeployment that correspond to these options are:

 ansibleTags
 ansibleSkipTags
 ansibleLimit

The syntax for these fields match the syntax that ansible accepts on the
command line for `ansible-playbook` and `ansible-runner` for each of these
fields.

Example usage of these fields:

 apiVersion: dataplane.openstack.org/v1beta1
 kind: OpenStackDataPlaneDeployment
 metadata:
   name: openstack-edpm
 spec:
   ansibleTags: containers
   ansibleSkipTags: packages
   ansibleLimit: compute1*,compute2*

The above example translates to an ansible command with the following
arguments:

 --tags containers --skip-tags packages --limit compute1*,compute2*
