= Interacting with Ansible

When a dataplane service is executed during a deployment, a corresponding
Kubernetes Job is created. This Kubernetes Job is the associated ansible
execution with the service.

During reconciliation a
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/[Job]
resource is created which in turn creates a
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/[Pod] resource. The pod is started with an https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html[Ansible Execution Environment] image, and runs https://ansible.readthedocs.io/projects/runner/en/stable/[ansible-runner].

== Retrieving and inspecting Ansible Execution Jobs

The Kubernetes jobs are labelled with the name of the `OpenStackDataPlaneDeployment`.
Jobs for each `OpenStackDataPlaneDeployment` can be seen by listing jobs by the label:

 $ oc get job -l openstackdataplanedeployment=edpm-compute
 NAME                                                 STATUS     COMPLETIONS   DURATION   AGE
 bootstrap-edpm-compute-openstack-edpm-ipam           Complete   1/1           78s        25h
 configure-network-edpm-compute-openstack-edpm-ipam   Complete   1/1           37s        25h
 configure-os-edpm-compute-openstack-edpm-ipam        Complete   1/1           66s        25h
 download-cache-edpm-compute-openstack-edpm-ipam      Complete   1/1           64s        25h
 install-certs-edpm-compute-openstack-edpm-ipam       Complete   1/1           46s        25h
 install-os-edpm-compute-openstack-edpm-ipam          Complete   1/1           57s        25h
 libvirt-edpm-compute-openstack-edpm-ipam             Complete   1/1           2m37s      25h
 neutron-metadata-edpm-compute-openstack-edpm-ipam    Complete   1/1           61s        25h
 nova-edpm-compute-openstack-edpm-ipam                Complete   1/1           3m20s      25h
 ovn-edpm-compute-openstack-edpm-ipam                 Complete   1/1           78s        25h
 run-os-edpm-compute-openstack-edpm-ipam              Complete   1/1           33s        25h
 ssh-known-hosts-edpm-compute                         Complete   1/1           19s        25h
 telemetry-edpm-compute-openstack-edpm-ipam           Complete   1/1           2m5s       25h
 validate-network-edpm-compute-openstack-edpm-ipam    Complete   1/1           16s        25h

Logs can be checked using `oc logs -f job/<job-name>`. For example, if we want to check the logs
from the configure-network job:

 $ oc logs -f jobs/configure-network-edpm-compute-openstack-edpm-ipam | tail -n2
PLAY RECAP *********************************************************************
edpm-compute-0             : ok=22   changed=0    unreachable=0    failed=0    skipped=17   rescued=0    ignored=0

== Controlling the Ansible execution

For specifying the
ansible https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#selecting-or-skipping-tags-when-you-run-a-playbook[tags, skip-tags],
and https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html#patterns-and-ad-hoc-commands[limit]

The fields in OpenStackDataPlaneDeployment that correspond to these options are:

 ansibleTags
 ansibleSkipTags
 ansibleLimit

The syntax for these fields match the syntax that ansible accepts on the
command line for `ansible-playbook` and `ansible-runner` for each of these
fields.

Example usage of these fields:

 apiVersion: dataplane.openstack.org/v1beta1
 kind: OpenStackDataPlaneDeployment
 metadata:
   name: openstack-edpm
 spec:
   ansibleTags: containers
   ansibleSkipTags: packages
   ansibleLimit: compute1*,compute2*

The above example translates to an ansible command with the following
arguments:

 --tags containers --skip-tags packages --limit compute1*,compute2*
