[id="proc_updating-the-data-plane-ovn-{context}"]
= Updating OVN on the data plane

[role="_abstract"]

You update OVN content (containers) on the data plane once OVN on the control
plane has been updated.

.Procedure

. Validate that OVN has been updated on the control plane.
+
----
$ oc wait openstackversion <openstack_ctlplane_name> --for=condition=MinorUpdateOVNControlplane
----
+
* Replace `<openstack_ctlplane_name>` with the name of the OpenStack control plane resource.
+
The following example output shows the condition has been met:
+
----
openstackversion.core.openstack.org/openstack-galera-network-isolation condition met
----

. Create an `OpenStackDataPlaneDeployment` CR and save it to a file named `openstack-edpm-update.yaml` on your workstation.
+
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: edpm-deployment-ipam-update
spec:
  nodeSets:
    - openstack-edpm-ipam
    - <nodeSet_name>
    - ...
    - <nodeSet_name>
  servicesOverride:
    - ovn
----
+
* Replace `<nodeSet_name>` with the names of the `OpenStackDataPlaneNodeSet` CRs that you want to include in your data plane minor update.
+
[NOTE]
The `servicesOverride` field is set to include only `ovn` as the `ovn` service must be updated first in isolation. If using a custom service to manage `ovn`, then use that custom service name instead of `ovn` in `servicesOverride`. Additionally if other custom services must be updated at the same time as `ovn`, then they can be included in `servicesOverride` as well.

. Save the `openstack-edpm-update.yaml` deployment file.

. Update the data plane:
+
----
$ oc create -f openstack-edpm-update.yaml
----

. Verify that the data plane update deployment succeeded:
+
----
$ oc get openstackdataplanedeployment
NAME             			STATUS   MESSAGE
edpm-deployment-ipam   		True     Setup Complete
edpm-deployment-ipam-update True     Setup Complete
----

Once OVN has been updated on the data plane, the rest of the control plane minor update will automatically proceed. Once the control plane minor update is finished, the rest of the data plane can be updated.

.Troubleshooting

See <<proc_troubleshooting-data-plane-creation-and-deployment_{context}>> for troubleshooting any deployment failures.
