[id="proc_creating-a-set-of-data-plane-nodes_{context}"]
= Creating a set of data plane nodes

[role="_abstract"]
You use the `OpenStackDataPlaneNodeSet` CRD to define the data plane and the data plane nodes. An `OpenStackDataPlaneNodeSet` custom resource (CR) represents a set of nodes of the same type that have similar configuration, comparable to the concept of a "role" in a director-deployed Red Hat OpenStack Platform (RHOSP) environment.

Create an `OpenStackDataPlaneNodeSet` CR for each logical grouping of nodes in your data plane, for example, nodes grouped by hardware, location, or networking. You can define as many node sets as necessary for your deployment. Each node can be included in only one `OpenStackDataPlaneNodeSet` CR. Each node set can be connected to only one Compute cell. By default, node sets are connected to `cell1`. If your control plane includes additional Compute cells, you must specify the cell to which the node set is connected.

.Procedure

. Create an `OpenStackDataPlaneNodeSet` CR and save it to a file named `openstack-edpm.yaml` on your workstation:
+
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  ...
----
+
* xref:ref_example-OpenStackDataPlaneNodeSet-CR-for-preprovisioned-nodes_dataplane[Example `OpenStackDataPlaneNodeSet` CR for pre-provisioned nodes]
* xref:ref_example-OpenStackDataPlaneNodeSet-CR-for-bare-metal-nodes_dataplane[Example `OpenStackDataPlaneNodeSet` CR for bare metal nodes]

. The sample `OpenStackDataPlaneNodeSet` CR is connected to `cell1` by default. If you added additional Compute cells to the control plane and you want to connect the node set to one of the other cells, then you must create a custom service for the node set that includes the `Secret` CR for the cell:

.. Create a custom `nova` service that includes the `Secret` CR for the cell to connect to:
+
[subs=+quotes]
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: *nova-cell-custom*
  spec:
    label: dataplane-deployment-custom-service
       playbook: osp.edpm.nova
    ...
    secrets:
      - nova-cell2-compute-config <1>
----
+
<1> The `Secret` CR generated by the control plane for the cell.
+
For information about how to create a custom service, see xref:proc_creating-a-custom-service_dataplane[Creating a custom service].

.. Replace the `nova` service in your `OpenStackDataPlaneNodeSet` CR with your custom `nova` service:
+
[subs=+quotes]
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  services:
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - run-os
    - ovn
    - libvirt
    - *nova-cell-custom*
    - telemetry
----
+
[NOTE]
Do not change the order of the default services.

. Update the `Secret` to the SSH key secret that you created to enable Ansible to connect to the data plane nodes:
+
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  nodeTemplate:
    ansibleSSHPrivateKeySecret: <secret-key>
----
+
* Replace `<secret-key>` with the name of the SSH key `Secret` CR you created in xref:proc_creating-the-SSH-key-secrets_dataplane[Creating the SSH key secrets], for example, `dataplane-ansible-ssh-private-key-secret`.

. Optional: Configure the node set for a Compute feature or workload. For more information, see xref:proc_configuring-a-node-set-for-a-Compute-feature-or-workload_{context}[Configuring a node set for a Compute feature or workload].

. Optional: The sample `OpenStackDataPlaneNodeSet` CR that you copied includes the minimum common configuration required for a set of nodes in this group under the `nodeTemplate` section. Each node in this `OpenStackDataPlaneNodeSet` inherits this configuration. You can edit the configured values as required, and you can add additional configuration.
+
For information about the properties you can use to configure common node attributes, see xref:ref_OpenStackDataPlaneNodeSet-CR-properties_dataplane[`OpenStackDataPlaneNodeSet` CR properties].
+
For example `OpenStackDataPlaneNodeSet` CR `nodeTemplate` definitions, see xref:ref_example-OpenStackDataPlaneNodeSet-CR-for-preprovisioned-nodes_dataplane[Example `OpenStackDataPlaneNodeSet` CR for pre-provisioned nodes] or xref:ref_example-OpenStackDataPlaneNodeSet-CR-for-bare-metal-nodes_dataplane[Example `OpenStackDataPlaneNodeSet` CR for bare metal nodes].

. Optional: The sample `OpenStackDataPlaneNodeSet` CR you copied applies the single NIC VLANs network configuration by default to the data plane nodes. You can edit the template that is applied. For example, to configure the data plane for multiple NICS, copy the contents of the `roles/edpm_network_config/templates/multiple_nics/multiple_nics.j2` file and add it to your `openstack-edpm.yaml` file:
+
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  ...
  nodeTemplate:
    ...
    ansible:
      ansibleVars:
        edpm_network_config_template: |
              ---
              network_config:
              - type: interface
                name: nic1
                mtu: {{ ctlplane_mtu }}
                dns_servers: {{ ctlplane_dns_nameservers }}
                domain: {{ dns_search_domains }}
                routes: {{ ctlplane_host_routes }}
                use_dhcp: false
                addresses:
                - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_subnet_cidr }}
                {% for network in nodeset_networks %}
                {% if network not in ["external", "tenant"] %}
                - type: interface
                  name: nic{{ loop.index +1 }}
                  mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                  use_dhcp: false
                  addresses:
                  - ip_netmask:
                    {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
                  routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
                {% elif 'external_bridge' in nodeset_tags|default([]) %}
                - type: ovs_bridge
                {% if network == 'external' %}
                  name: {{ neutron_physical_bridge_name }}
                {% else %}
                  name: {{ 'br-' ~ networks_lower[network] }}
                {% endif %}
                  mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                  dns_servers: {{ ctlplane_dns_nameservers }}
                  use_dhcp: false
                  addresses:
                  - ip_netmask:
                    {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
                  routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
                  members:
                  - type: interface
                    name: nic{{loop.index + 1}}
                    mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                    use_dhcp: false
                    primary: true
                {% endif %}
                {% endfor %}
----
+
You can copy a sample template from https://github.com/openstack-k8s-operators/openstack-operator/tree/main/config/samples/nic-config-samples. For information about customizing the template, see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.1/html/installing_and_managing_red_hat_openstack_platform_with_director/assembly_configuring-overcloud-networking_installing-director-on-the-undercloud#ref_network-interface-configuration-options_custom-network-interface-templates[Network interface configuration options].
ifeval::["{build}" == "downstream"]
. Register the operating system of the nodes that are not registered to the Red Hat Customer Portal, and enable repositories for your nodes:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: subscription-manager
data:
  username: <subscription_manager_username>
  password: <subscription_manager_password>
----
+
* Replace `<subscription_manager_username>` with the applicable user name.
* Replace `<subscription_manager_password>` with the applicable password.

+
----
$ oc create secret generic redhat-registry \
--from-literal edpm_container_registry_logins='{"registry.redhat.io": {"<registry_username>": "<registry_password>"}}'
----
+
* Replace `<registry_username>` with the applicable user name.
* Replace `<registry_password>` with the applicable password.

+
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  preProvisioned: True
  ...
  nodeTemplate:
    ansible:
      ...
      ansibleVars:
        edpm_bootstrap_command: |
          subscription-manager register --username {{ subscription_manager_username }} --password {{ subscription_manager_password }}
          subscription-manager release --set=9.2
          subscription-manager repos --disable=*
          subscription-manager repos --enable=rhel-9-for-x86_64-baseos-eus-rpms --enable=rhel-9-for-x86_64-appstream-eus-rpms --enable=rhel-9-for-x86_64-highavailability-eus-rpms --enable=openstack-17.1-for-rhel-9-x86_64-rpms --enable=fast-datapath-for-rhel-9-x86_64-rpms --enable=openstack-dev-preview-for-rhel-9-x86_64-rpms
      ansibleVarsFrom:
      - prefix: subscription_manager_
        secretRef:
          name: subscription-manager
      - secretRef:
          name: redhat-registry
----

+
For a complete list of the Red Hat Customer Portal registration commands, see https://access.redhat.com/solutions/253273. For information about how to log into `registry.redhat.io`, see https://access.redhat.com/RegistryAuthentication#creating-registry-service-accounts-6.
endif::[]
. If your nodes are bare metal, you must configure the bare metal template, see xref:con_provisioning-bare-metal-data-plane-nodes_{context}[Provisioning bare metal data plane nodes].

. Optional: The sample `OpenStackDataPlaneNodeSet` CR you copied includes default node configurations under the `nodes` section. You can add additional nodes, and edit the configured values as required. For example, to add node-specific Ansible variables that customize the node, add the following configuration to your `openstack-edpm.yaml` file:
+
----
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  ...
  nodes:
    edpm-compute-0: <1>
      hostName: edpm-compute-0
      ansible:
        ansibleHost: 192.168.122.100
        ansibleVars: <2>
          ctlplane_ip: 192.168.122.100
          internalapi_ip: 172.17.0.100
          storage_ip: 172.18.0.100
          tenant_ip: 172.19.0.100
          fqdn_internalapi: edpm-compute-0.example.com
    edpm-compute-1:
      hostName: edpm-compute-1
      ansible:
        ansibleHost: 192.168.122.101
        ansibleVars:
          ctlplane_ip: 192.168.122.101
          internalapi_ip: 172.17.0.101
          storage_ip: 172.18.0.101
          tenant_ip: 172.19.0.101
          fqdn_internalapi: edpm-compute-1.example.com
----
+
<1> The node definition reference, for example, `edpm-compute-0`. Each node in the node set must have a node definition.
<2> Node-specific Ansible variables that customize the node.

+
[NOTE]
====
* Nodes defined within the `nodes` section can configure the same Ansible variables that are configured in the `nodeTemplate` section. Where an Ansible variable is configured for both a specific node and within the `nodeTemplate` section, the node-specific values override those from the `nodeTemplate` section.
* You do not need to replicate all the `nodeTemplate` Ansible variables for a node to override the default and set some node-specific values. You only need to configure the Ansible variables you want to override for the node.
====

+
For information about the properties you can use to configure node attributes, see xref:ref_OpenStackDataPlaneNodeSet-CR-properties_dataplane[`OpenStackDataPlaneNodeSet` CR properties]. For example `OpenStackDataPlaneNodeSet` CR `nodes` definitions, see xref:ref_example-OpenStackDataPlaneNodeSet-CR-for-preprovisioned-nodes_dataplane[Example `OpenStackDataPlaneNodeSet` CR for pre-provisioned nodes] or xref:ref_example-OpenStackDataPlaneNodeSet-CR-for-bare-metal-nodes_dataplane[Example `OpenStackDataPlaneNodeSet` CR for bare metal nodes].

. Optional: Customize the container images used by the `edpm-ansible` roles. The following example shows the default images:
+
----
spec:
  ...
  nodeTemplate:
    ...
    ansible:
      ...
      ansibleVars:
ifeval::["{build}" != "downstream"]
        edpm_iscsid_image: "quay.io/podified-antelope-centos9/openstack-iscsid:current-podified"
        edpm_logrotate_crond_image: "quay.io/podified-antelope-centos9/openstack-cron:current-podified"
        edpm_ovn_controller_agent_image: "quay.io/podified-antelope-centos9/openstack-frr:current-podified"
        edpm_ovn_metadata_agent_image: "quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified"
        edpm_frr_image: "quay.io/podified-antelope-centos9/openstack-frr:current-podified"
        edpm_ovn_bgp_agent_image: "quay.io/podified-antelope-centos9/openstack-ovn-bgp-agent:current-podified"
        telemetry_node_exporter_image: "quay.io/prometheus/node-exporter:v1.5.0"
        edpm_telemetry_kepler_image: "quay.io/sustainable_computing_io/kepler"
        edpm_libvirt_image: "quay.io/podified-antelope-centos9/openstack-nova-libvirt:current-podified"
        edpm_nova_compute_image: "quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified"
        edpm_neutron_sriov_image: "quay.io/podified-antelope-centos9/openstack-neutron-sriov-agent:current-podified"
        edpm_multipathd_image: "quay.io/podified-antelope-centos9/openstack-multipathd:current-podified"
endif::[]
ifeval::["{build}" == "downstream"]
        edpm_iscsid_image: "registry.redhat.io/rhosp-dev-preview/openstack-iscsid:18.0"
        edpm_logrotate_crond_image: "registry.redhat.io/rhosp-dev-preview/openstack-cron:18.0"
        edpm_ovn_controller_agent_image: "registry.redhat.io/rhosp-dev-preview/openstack-frr:18.0"
        edpm_ovn_metadata_agent_image: "registry.redhat.io/rhosp-dev-preview/openstack-neutron-metadata-agent-ovn:18.0"
        edpm_frr_image: "registry.redhat.io/rhosp-dev-preview/openstack-frr:18.0"
        edpm_ovn_bgp_agent_image: "registry.redhat.io/rhosp-dev-preview/openstack-ovn-bgp-agent:18.0"
        telemetry_node_exporter_image: "quay.io/prometheus/node-exporter:v1.5.0"
        edpm_telemetry_kepler_image: "registry.redhat.io/openshift-power-monitoring/kepler-rhel9:v0.7.10-2"
        edpm_libvirt_image: "registry.redhat.io/rhosp-dev-preview/openstack-nova-libvirt:18.0"
        edpm_nova_compute_image: "registry.redhat.io/rhosp-dev-preview/openstack-nova-compute:18.0"
        edpm_neutron_sriov_image: "registry.redhat.io/rhosp-dev-preview/openstack-neutron-sriov-agent:18.0"
        edpm_multipathd_image: "registry.redhat.io/rhosp-dev-preview/openstack-multipathd:18.0"
endif::[]
----

. Save the `openstack-edpm.yaml` definition file.

. Create the data plane resources:
+
----
$ oc create -f openstack-edpm.yaml
----

. Verify that the data plane resources have been created:
+
----
$ oc get openstackdataplanenodeset
NAME           		STATUS MESSAGE
openstack-edpm-ipam 	False  Deployment not started
----

. Verify that the `Secret` resource was created for the node set:
+
----
$ oc get secret | grep openstack-edpm-ipam
dataplanenodeset-openstack-edpm-ipam Opaque 1 3m50s
----

. Verify the services were created:
+
----
$ oc get openstackdataplaneservice
NAME                AGE
configure-network   6d7h
configure-os        6d6h
install-os          6d6h
run-os              6d6h
validate-network    6d6h
ovn                 6d6h
libvirt             6d6h
nova                6d6h
telemetry           6d6h
----
