[id="proc_creating-the-SSH-key-secrets_{context}"]
= Creating the SSH key secrets

[role="_abstract"]
You must generate SSH keys and create an SSH key `Secret` custom resource (CR) for each key to enable the following functionality:

ifeval::["{build}" != "downstream"]
* You must generate an SSH key to enable Ansible to manage the CentOS nodes on the data plane. Ansible executes commands with this user and key.
endif::[]
ifeval::["{build}" == "downstream"]
* You must generate an SSH key to enable Ansible to manage the RHEL nodes on the data plane. Ansible executes commands with this user and key.
endif::[]
* You must generate an SSH key to enable migration of instances between Compute nodes.

The `Secret` CRs are used by the data plane nodes to enable secure access between nodes.

.Procedure

. Create the SSH key pair for Ansible:
+
----
$ KEY_FILE_NAME=<key_file_name>
$ ssh-keygen -f $KEY_FILE_NAME -N "" -t rsa -b 4096
----
+
* Replace `<key_file_name>` with the name to use for the key pair.

. Create the `Secret` CR for Ansible and apply it to the cluster:
+
----
$ SECRET_NAME=<secret_name>
$ oc create secret generic $SECRET_NAME \
--save-config \
--dry-run=client \
[--from-file=authorized_keys=$KEY_FILE_NAME.pub \]
--from-file=ssh-privatekey=$KEY_FILE_NAME \
--from-file=ssh-publickey=$KEY_FILE_NAME.pub \
-n openstack \
-o yaml | oc apply -f-
----
+
* Replace `<secret_name>` with the name you want to use for the `Secret` resource.
* Include the `--from-file=authorized_keys` option for bare metal nodes that must be provisioned when creating the data plane.

. Create the SSH key pair for instance migration:
+
----
$ ssh-keygen -f ./id -t ecdsa-sha2-nistp521 -N ''
----

. Create the `Secret` CR for migration and apply it to the cluster:
+
----
$ oc create secret generic nova-migration-ssh-key \
--from-file=ssh-privatekey=id \
--from-file=ssh-publickey=id.pub \
-n openstack \
-o yaml | oc apply -f-
----

. Verify that the `Secret` CRs are created:
+
----
$ oc describe secret $SECRET_NAME`
----
