version: 2

linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errorlint
    - revive
    - ginkgolinter
    - govet

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
