resources:
- core_v1beta1_openstackcontrolplane.yaml
patches:
  - target:
      kind: OpenStackControlPlane
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: openstack
