# permissions for end users to view openstackclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackclient-viewer-role
rules:
- apiGroups:
  - core.openstack.org
  resources:
  - openstackclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackclients/status
  verbs:
  - get
