# permissions for end users to view openstacklightspeeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstacklightspeed-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/part-of: openstack-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacklightspeed-viewer-role
rules:
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds/status
  verbs:
  - get
