apiVersion: operator.openstack.org/v1beta1
kind: OpenStack
metadata:
  labels:
    app.kubernetes.io/name: openstack
    app.kubernetes.io/instance: openstack
    app.kubernetes.io/part-of: openstack-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openstack-operator
  name: openstack
  namespace: openstack-operators
spec:
  operatorOverrides:
  - name: infra
    controllerManager:
      resources:
        limits:
          cpu: 600m
          memory: 2Gi
    replicas: 1
