/*
Copyright 2023.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group client --version v1beta1 --kind OpenStackClient --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// OpenStackClientDefaults -
type OpenStackClientDefaults struct {
	ContainerImageURL string
}

var openStackClientDefaults OpenStackClientDefaults

// log is for logging in this package.
var openstackclientlog = logf.Log.WithName("openstackclient-resource")

// SetupOpenStackClientDefaults - initialize OpenStackClient spec defaults for use with either internal or external webhooks
func SetupOpenStackClientDefaults(defaults OpenStackClientDefaults) {
	openStackClientDefaults = defaults
	openstackclientlog.Info("OpenStackClient defaults initialized", "defaults", defaults)
}

// Default sets default values for the OpenStackClient
func (r *OpenStackClient) Default() {
	openstackclientlog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this OpenStackClient spec
func (spec *OpenStackClientSpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = openStackClientDefaults.ContainerImageURL
	}
}

// ValidateCreate validates the OpenStackClient on creation
func (r *OpenStackClient) ValidateCreate() (admission.Warnings, error) {
	openstackclientlog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackClient) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	openstackclientlog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackClient) ValidateDelete() (admission.Warnings, error) {
	openstackclientlog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
