apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  tls:
    ingress:
      cert:
        duration: 500h0m0s
    podLevel:
      internal:
        cert:
          duration:  500h0m0s
      libvirt:
        cert:
          duration:  500h0m0s
      ovn:
        cert:
          duration:  500h0m0s
