apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openstack

components:
- ../preprovisioned # for baremetal nodes, replace with baremetal

resources:
  - values.yaml

replacements:
# OpenStackDataPlaneNodeSet customizations
- source:
    kind: DataPlaneConfig
    name: edpm-swift-values
    fieldPath: data.nodeset.nodeTemplate.ansible.ansibleVars.edpm_swift_disks
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars.edpm_swift_disks
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-swift-values
    fieldPath: data.nodeset.services
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.services
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-swift-values
    fieldPath: data.nodeset.networkAttachments
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.networkAttachments
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-swift-values
    fieldPath: data.nodeset.nodes
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodes
    options:
      create: true
