apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openstack-operator
  name: openstack-operator-controller-manager
  namespace: '{{ .OperatorNamespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openstack-operator
  name: openstack-operator-leader-election-role
  namespace: '{{ .OperatorNamespace }}'
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstack-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - imagestreamimages
  - imagestreammappings
  - imagestreams
  - imagestreams/layers
  - imagestreamtags
  - imagetags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  - project.openshift.io
  resources:
  - projects
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - barbican.openstack.org
  resources:
  - barbicans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackbaremetalsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackbaremetalsets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackbaremetalsets/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.openstack.org
  resources:
  - openstackclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.openstack.org
  resources:
  - openstackclients/finalizers
  verbs:
  - update
- apiGroups:
  - client.openstack.org
  resources:
  - openstackclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - imagedigestmirrorsets
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackcontrolplanes
  - openstackversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackcontrolplanes/finalizers
  - openstackversions/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - core.openstack.org
  resources:
  - openstackcontrolplanes/status
  - openstackversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanedeployments/finalizers
  - openstackdataplanenodesets/finalizers
  - openstackdataplaneservices/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanedeployments/status
  - openstackdataplanenodesets/status
  - openstackdataplaneservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodesets
  - openstackdataplaneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - glance.openstack.org
  resources:
  - glances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - horizon.openstack.org
  resources:
  - horizons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreamimages
  - imagestreammappings
  - imagestreams
  - imagestreamtags
  - imagetags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams/layers
  verbs:
  - get
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - galeras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata
  - dnsmasqs
  - ipsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata/finalizers
  - ipsets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata/status
  - dnsmasqs/status
  - ipsets/status
  verbs:
  - get
- apiGroups:
  - network.openstack.org
  resources:
  - netconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - nova
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octavias
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - imagecontentsourcepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - installplans
  - operators
  - subscriptions
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncontrollers
  - ovndbclusters
  - ovnnorthds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - rabbitmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - redis.openstack.org
  resources:
  - redises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - swift.openstack.org
  resources:
  - swifts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - metricstorages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - telemetries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.openstack.org
  resources:
  - topologies
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstack-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstack-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openstack-operator
  name: openstack-operator-leader-election-rolebinding
  namespace: '{{ .OperatorNamespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstack-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: openstack-operator-controller-manager
  namespace: '{{ .OperatorNamespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openstack-operator
  name: openstack-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-operator-manager-role
subjects:
- kind: ServiceAccount
  name: openstack-operator-controller-manager
  namespace: '{{ .OperatorNamespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openstack-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: openstack-operator-controller-manager
  namespace: '{{ .OperatorNamespace }}'
