//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackBackupConfig) DeepCopyInto(out *OpenStackBackupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackBackupConfig.
func (in *OpenStackBackupConfig) DeepCopy() *OpenStackBackupConfig {
	if in == nil {
		return nil
	}
	out := new(OpenStackBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackBackupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackBackupConfigList) DeepCopyInto(out *OpenStackBackupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackBackupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackBackupConfigList.
func (in *OpenStackBackupConfigList) DeepCopy() *OpenStackBackupConfigList {
	if in == nil {
		return nil
	}
	out := new(OpenStackBackupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackBackupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackBackupConfigSpec) DeepCopyInto(out *OpenStackBackupConfigSpec) {
	*out = *in
	in.Secrets.DeepCopyInto(&out.Secrets)
	in.ConfigMaps.DeepCopyInto(&out.ConfigMaps)
	in.NetworkAttachmentDefinitions.DeepCopyInto(&out.NetworkAttachmentDefinitions)
	in.Issuers.DeepCopyInto(&out.Issuers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackBackupConfigSpec.
func (in *OpenStackBackupConfigSpec) DeepCopy() *OpenStackBackupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackBackupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackBackupConfigStatus) DeepCopyInto(out *OpenStackBackupConfigStatus) {
	*out = *in
	out.LabeledResources = in.LabeledResources
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackBackupConfigStatus.
func (in *OpenStackBackupConfigStatus) DeepCopy() *OpenStackBackupConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackBackupConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceBackupConfig) DeepCopyInto(out *ResourceBackupConfig) {
	*out = *in
	if in.Labeling != nil {
		in, out := &in.Labeling, &out.Labeling
		*out = new(BackupLabelingPolicy)
		**out = **in
	}
	if in.ExcludeLabelKeys != nil {
		in, out := &in.ExcludeLabelKeys, &out.ExcludeLabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNames != nil {
		in, out := &in.ExcludeNames, &out.ExcludeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeLabelSelector != nil {
		in, out := &in.IncludeLabelSelector, &out.IncludeLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceBackupConfig.
func (in *ResourceBackupConfig) DeepCopy() *ResourceBackupConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceCounts) DeepCopyInto(out *ResourceCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceCounts.
func (in *ResourceCounts) DeepCopy() *ResourceCounts {
	if in == nil {
		return nil
	}
	out := new(ResourceCounts)
	in.DeepCopyInto(out)
	return out
}
