apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: infra-operator
    app.kubernetes.io/part-of: infra-operator
  name: infra-operator-webhook-service
  namespace: '{{ .OperatorNamespace }}'
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: infra-operator
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: infra-operator
  name: infra-operator-serving-cert
  namespace: '{{ .OperatorNamespace }}'
spec:
  dnsNames:
  - infra-operator-webhook-service.{{ .OperatorNamespace }}.svc
  - infra-operator-webhook-service.{{ .OperatorNamespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: infra-operator-selfsigned-issuer
  secretName: infra-operator-webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .OperatorNamespace }}/infra-operator-serving-cert'
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/part-of: infra-operator
  name: infra-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mdnsmasq-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - dnsmasqs
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-network-openstack-org-v1beta1-dnsmasq
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: minstanceha-v1beta1.kb.io
  rules:
    - apiGroups:
        - instanceha.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - instancehas
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-instanceha-openstack-org-v1beta1-instanceha
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mipset-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - ipsets
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-network-openstack-org-v1beta1-ipset
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mmemcached-v1beta1.kb.io
  rules:
    - apiGroups:
        - memcached.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - memcacheds
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-memcached-openstack-org-v1beta1-memcached
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mnetconfig-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - netconfigs
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-network-openstack-org-v1beta1-netconfig
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmq-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqs
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmq
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmqpolicy-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqpolicies
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmqpolicy
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmqpolicy.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqpolicies
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmqpolicy
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmquser-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqusers
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmquser
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmquser.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqusers
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmquser
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmqvhost-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqvhosts
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmqvhost
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mrabbitmqvhost.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqvhosts
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmqvhost
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mredis-v1beta1.kb.io
  rules:
    - apiGroups:
        - redis.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - redises
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-redis-openstack-org-v1beta1-redis
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: mreservation-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - reservations
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-network-openstack-org-v1beta1-reservation
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .OperatorNamespace }}/infra-operator-serving-cert'
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: infra-operator
  name: infra-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vdnsmasq-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - dnsmasqs
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-network-openstack-org-v1beta1-dnsmasq
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vinstanceha-v1beta1.kb.io
  rules:
    - apiGroups:
        - instanceha.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - instancehas
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-instanceha-openstack-org-v1beta1-instanceha
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vipset-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - ipsets
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-network-openstack-org-v1beta1-ipset
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vmemcached-v1beta1.kb.io
  rules:
    - apiGroups:
        - memcached.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - memcacheds
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-memcached-openstack-org-v1beta1-memcached
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vnetconfig-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
        - DELETE
      resources:
        - netconfigs
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-network-openstack-org-v1beta1-netconfig
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmq-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqs
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmq
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmqpolicy-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqpolicies
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmqpolicy
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmqpolicy.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqpolicies
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmqpolicy
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmquser-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqusers
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmquser
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmquser.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqusers
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmquser
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmqvhost-v1beta1.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqvhosts
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmqvhost
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vrabbitmqvhost.kb.io
  rules:
    - apiGroups:
        - rabbitmq.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - rabbitmqvhosts
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmqvhost
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vredis-v1beta1.kb.io
  rules:
    - apiGroups:
        - redis.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - redises
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-redis-openstack-org-v1beta1-redis
- admissionReviewVersions:
  - v1
  failurePolicy: Fail
  name: vreservation-v1beta1.kb.io
  rules:
    - apiGroups:
        - network.openstack.org
      apiVersions:
      - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - reservations
  sideEffects: None
  clientConfig:
    service:
      name: infra-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-network-openstack-org-v1beta1-reservation
