{{ $namespace := .OperatorNamespace }}
{{ $kubeRbacProxyImage := .KubeRbacProxyImage }}
{{ $leaseDuration := .LeaseDuration }}
{{ $renewDeadline := .RenewDeadline }}
{{ $retryPeriod := .RetryPeriod }}
{{ range $operatorName, $operatorImage := .OperatorImages }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    openstack.org/operator-name: {{ $operatorName }}
  name: {{ $operatorName }}-operator-controller-manager
  namespace: {{ $namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      openstack.org/operator-name: {{ $operatorName }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        openstack.org/operator-name: {{ $operatorName }}
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ENABLE_WEBHOOKS
{{ if or (eq $operatorName "infra") (eq $operatorName "openstack-baremetal") }}
          value: 'true'
{{ else }}
          value: 'false'
{{ end }}
        - name: LEASE_DURATION
          value: '{{ $leaseDuration }}'
        - name: RENEW_DEADLINE
          value: '{{ $renewDeadline }}'
        - name: RETRY_PERIOD
          value: '{{ $retryPeriod }}'
        image: {{ $operatorImage }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
{{ if or (eq $operatorName "infra") (eq $operatorName "openstack-baremetal") }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
{{ end }}
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: {{ $kubeRbacProxyImage }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ $operatorName }}-operator-controller-manager
      terminationGracePeriodSeconds: 10
{{ if or (eq $operatorName "infra") (eq $operatorName "openstack-baremetal") }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ $operatorName }}-operator-webhook-server-cert
{{ end }}
---
{{ end }}
