apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    openstack.org/operator-name: openstack
  name: '{{ .OperatorNamespace }}'
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 40ba705e.openstack.org
kind: ConfigMap
metadata:
  name: openstack-operator-manager-config
  namespace: '{{ .OperatorNamespace }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: openstack-operator
  name: openstack-operator-webhook-service
  namespace: '{{ .OperatorNamespace }}'
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    openstack.org/operator-name: openstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    openstack.org/operator-name: openstack
  name: openstack-operator-controller-manager
  namespace: '{{ .OperatorNamespace }}'
spec:
  replicas: {{ .OpenStackOperator.Deployment.Replicas }}
  selector:
    matchLabels:
      openstack.org/operator-name: openstack
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        openstack.org/operator-name: openstack
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
{{- range .OpenStackOperator.Deployment.Manager.Env }}
        - name: '{{ .Name }}'
          value: '{{ .Value }}'
{{- end }}
        image: '{{ .OpenStackOperator.Deployment.Manager.Image }}'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: {{ .OpenStackOperator.Deployment.Manager.Resources.Limits.CPU }}
            memory: {{ .OpenStackOperator.Deployment.Manager.Resources.Limits.Memory }}
          requests:
            cpu: {{ .OpenStackOperator.Deployment.Manager.Resources.Requests.CPU }}
            memory: {{ .OpenStackOperator.Deployment.Manager.Resources.Requests.Memory }}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: '{{ .OpenStackOperator.Deployment.KubeRbacProxy.Image }}'
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
      tolerations:
{{- range .OpenStackOperator.Deployment.Tolerations }}
      - key: "{{ .Key }}"
{{- if .Operator }}
        operator: "{{ .Operator }}"
{{- end }}
{{- if .Value }}
        value: "{{ .Value }}"
{{- end }}
{{- if .Effect }}
        effect: "{{ .Effect }}"
{{- end }}
{{- if .TolerationSeconds }}
        tolerationSeconds: {{ .TolerationSeconds }}
{{- end }}
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: openstack-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: openstack-operator
  name: openstack-operator-serving-cert
  namespace: '{{ .OperatorNamespace }}'
spec:
  dnsNames:
  - openstack-operator-webhook-service.{{ .OperatorNamespace }}.svc
  - openstack-operator-webhook-service.{{ .OperatorNamespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: openstack-operator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: issuer
    app.kubernetes.io/part-of: openstack-operator
  name: openstack-operator-selfsigned-issuer
  namespace: '{{ .OperatorNamespace }}'
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .OperatorNamespace }}/openstack-operator-serving-cert'
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingingwebhookconfiguration
    app.kubernetes.io/part-of: openstack-operator
  name: openstack-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-client-openstack-org-v1beta1-openstackclient
  failurePolicy: Fail
  name: mopenstackclient.kb.io
  rules:
  - apiGroups:
    - client.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-core-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: mopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-core-openstack-org-v1beta1-openstackversion
  failurePolicy: Fail
  name: mopenstackversion.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-dataplane-openstack-org-v1beta1-openstackdataplanedeployment
  failurePolicy: Fail
  name: mopenstackdataplanedeployment.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanedeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-dataplane-openstack-org-v1beta1-openstackdataplanenodeset
  failurePolicy: Fail
  name: mopenstackdataplanenodeset.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanenodesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /mutate-dataplane-openstack-org-v1beta1-openstackdataplaneservice
  failurePolicy: Fail
  name: mopenstackdataplaneservice.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplaneservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .OperatorNamespace }}/openstack-operator-serving-cert'
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: openstack-operator
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: openstack-operator
  name: openstack-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-client-openstack-org-v1beta1-openstackclient
  failurePolicy: Fail
  name: vopenstackclient.kb.io
  rules:
  - apiGroups:
    - client.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-core-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: vopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-core-openstack-org-v1beta1-openstackversion
  failurePolicy: Fail
  name: vopenstackversion.kb.io
  rules:
  - apiGroups:
    - core.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-dataplane-openstack-org-v1beta1-openstackdataplanedeployment
  failurePolicy: Fail
  name: vopenstackdataplanedeployment.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanedeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-dataplane-openstack-org-v1beta1-openstackdataplanenodeset
  failurePolicy: Fail
  name: vopenstackdataplanenodeset.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplanenodesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: openstack-operator-webhook-service
      namespace: '{{ .OperatorNamespace }}'
      path: /validate-dataplane-openstack-org-v1beta1-openstackdataplaneservice
  failurePolicy: Fail
  name: vopenstackdataplaneservice.kb.io
  rules:
  - apiGroups:
    - dataplane.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdataplaneservices
  sideEffects: None
