apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator-manager
  namespace: {{ .RabbitmqOperator.Namespace }}
spec:
  replicas: {{ .RabbitmqOperator.Deployment.Replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- range .RabbitmqOperator.Deployment.Manager.Env }}
        - name: '{{ .Name }}'
          value: '{{ .Value }}'
{{- end }}
        image: {{ .RabbitmqOperator.Deployment.Manager.Image }}
        name: operator
        ports:
        - containerPort: 9782
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: {{ .RabbitmqOperator.Deployment.Manager.Resources.Limits.CPU }}
            memory: {{ .RabbitmqOperator.Deployment.Manager.Resources.Limits.Memory }}
          requests:
            cpu: {{ .RabbitmqOperator.Deployment.Manager.Resources.Requests.CPU }}
            memory: {{ .RabbitmqOperator.Deployment.Manager.Resources.Requests.Memory }}
      serviceAccountName: rabbitmq-cluster-operator-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
