apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator-manager
  namespace: {{ .OperatorNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEASE_DURATION
          value: '{{ .LeaseDuration }}'
        - name: RENEW_DEADLINE
          value: '{{ .RenewDeadline }}'
        - name: RETRY_PERIOD
          value: '{{ .RetryPeriod }}'
        image: {{ .RabbitmqImage }}
        name: operator
        ports:
        - containerPort: 9782
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: '{{ .ManagerMemoryLimit }}'
          requests:
            cpu: 5m
            memory: 64Mi
      serviceAccountName: rabbitmq-cluster-operator-controller-manager
      terminationGracePeriodSeconds: 10
