# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.openstack.org_openstackcontrolplanes.yaml
- bases/client.openstack.org_openstackclients.yaml
- bases/core.openstack.org_openstackversions.yaml
- bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
- bases/dataplane.openstack.org_openstackdataplaneservices.yaml
- bases/dataplane.openstack.org_openstackdataplanedeployments.yaml
#- bases/operator.openstack.org_openstacks.yaml
- bases/backup.openstack.org_openstackbackupconfigs.yaml
- bases/assistant.openstack.org_openstackassistants.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] patches for enabling the conversion webhook for each CRD
- path: patches/webhook_in_core.openstack.org_openstackcontrolplanes.yaml
- path: patches/webhook_in_dataplane.openstack.org_openstackdataplanenodesets.yaml
- path: patches/webhook_in_dataplane.openstack.org_openstackdataplaneservices.yaml
- path: patches/webhook_in_dataplane.openstack.org_openstackdataplanedeployments.yaml
- path: patches/webhook_in_core.openstack.org_openstackversions.yaml
- path: patches/webhook_in_client.openstack.org_openstackclients.yaml
- path: patches/webhook_in_backup.openstack.org_openstackbackupconfigs.yaml
- path: patches/webhook_in_assistant.openstack.org_openstackassistants.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] patches for enabling the CA injection for each CRD
- path: patches/cainjection_in_core.openstack.org_openstackcontrolplanes.yaml
- path: patches/cainjection_in_dataplane.openstack.org_openstackdataplanenodesets.yaml
- path: patches/cainjection_in_dataplane.openstack.org_openstackdataplaneservices.yaml
- path: patches/cainjection_in_dataplane.openstack.org_openstackdataplanedeployments.yaml
- path: patches/cainjection_in_core.openstack.org_openstackversions.yaml
- path: patches/cainjection_in_client.openstack.org_openstackclients.yaml
- path: patches/cainjection_in_backup.openstack.org_openstackbackupconfigs.yaml
- path: patches/cainjection_in_assistant.openstack.org_openstackassistants.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
