apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  barbican:
    apiOverride:
      tls:
        secretName: barbican-custom-route
  placement:
    apiOverride:
      route:
        spec:
          tls:
            certificate: ""
            key: ""
            caCertificate: ""
            termination: reencrypt
