apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openstack
nameSuffix: -networker

components:
- ../preprovisioned # for baremetal nodes, replace with baremetal

resources:
  - values.yaml

replacements:
# OpenStackDataPlaneNodeSet customizations
- source:
    kind: DataPlaneConfig
    name: edpm-networker-values
    fieldPath: data.nodeset.nodetemplate.ansible.vars.edpm_enable_chassis_gw
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodeTemplate.ansible.ansibleVars.edpm_enable_chassis_gw
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-networker-values
    fieldPath: data.nodeset.services
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.services
    options:
      create: true
- source:
    kind: DataPlaneConfig
    name: edpm-networker-values
    fieldPath: data.nodeset.nodes
  targets:
  - select:
      kind: OpenStackDataPlaneNodeSet
    fieldPaths:
    - spec.nodes
    options:
      create: true
