# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: DataPlaneConfig
metadata:
  name: edpm-networker-ovs-dpdk-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  preProvisioned: false
  nodeset:
    baremetalsettemplate:
      bmhLabelSelector:
        app: openstack
      ctlplaneInterface: enp1s0
      cloudUserName: cloud-admin
    nodetemplate:
      ansible:
        vars:
          edpm_network_config_hide_sensitive_logs: false
      edpm_network_config_os_net_config_mappings:
          # Need to provide nic mapping based on system uuid or system product name
          # here used systetm uuid
          edpm-networker-0:  # CHANGEME
            nic1: 6c:fe:54:3f:8a:01  # CHANGEME
            nic2: 6c:fe:54:3f:8a:02  # CHANGEME
            nic3: 6c:fe:54:3f:8a:03  # CHANGEME
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          network_config:
          - type: linux_bond
            name: bond_api
            bonding_options: "mode=active-backup"
            use_dhcp: false
            dns_servers: {{ ctlplane_dns_nameservers }}
            members:
            - type: interface
              name: nic1
            addresses:
            - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
            routes:
            - default: true
              next_hop: {{ ctlplane_gateway_ip }}
          {% for network in nodeset_networks if network not in ['external', 'tenant'] %}
            - type: vlan
              mtu: {{ lookup('ars', networks_lower[network] ~ '_mtu') }}
              vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
              addresses:
              - ip_netmask: {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
          {% endfor %}
          - type: ovs_user_bridge
            name: br-link1
            use_dhcp: false
            ovs_extra: "set port br-link1 tag={{ lookup('vars', networks_lower['tenant'] ~ '_vlan_id') }}"
            addresses:
            - ip_netmask: {{ lookup('vars', networks_lower['tenant'] ~ '_ip') }}/{{ lookup('vars', networks_lower['tenant'] ~ '_cidr') }}
            mtu: {{ lookup('vars', networks_lower['tenant'] ~ '_mtu') }}
            members:
            - type: ovs_dpdk_port
              name: dpdk1
              members:
              - type: interface
                name: nic2
          - type: ovs_user_bridge
            name: br-link2
            use_dhcp: false
            mtu: 9000
            members:
            - type: ovs_dpdk_port
              name: dpdk2
              members:
              - type: interface
                name: nic3

          # edpm_nodes_validation
          edpm_nodes_validation_validate_controllers_icmp: false
          edpm_nodes_validation_validate_gateway_icmp: false
          # edpm nfv ovs dpdk config
          edpm_kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on tsx=off isolcpus=2-11,14-23"
          edpm_tuned_profile: "cpu-partitioning"
          edpm_tuned_isolated_cores: "2-11,14-23"
          edpm_ovs_dpdk_pmd_core_list: "1,13,2,14,3,15"
          edpm_ovs_dpdk_socket_memory: "4096"
          edpm_ovs_dpdk_memory_channels: "4"
          edpm_ovs_dpdk_vhost_postcopy_support: "true"
          edpm_ovn_bridge_mappings: ['dpdk2:br-link2','dpdk1:br-link1']
          gather_facts: false
          enable_debug: false
          edpm_sshd_allowed_ranges: ['192.168.122.0/24']
  nodeset:
    nodetemplate:
      ansible:
        vars:
          edpm_enable_chassis_gw: true
    nodes:
      edpm-networker-0:
        hostName: edpm-networker-0
        ansible:
          ansibleHost: 192.168.122.100
        networks:
          - name: ctlplane
            subnetName: subnet1
            defaultRoute: true
            fixedIP: 192.168.122.100
          - name: internalapi
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1
    services:
    - bootstrap
    - download-cache
    - reboot-os
    - configure-ovs-dpdk
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - ssh-known-hosts
    - run-os
    - install-certs
    - ovn
    - neutron-ovn
    - neutron-metadata
