//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeed) DeepCopyInto(out *OpenStackLightspeed) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeed.
func (in *OpenStackLightspeed) DeepCopy() *OpenStackLightspeed {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackLightspeed) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedCore) DeepCopyInto(out *OpenStackLightspeedCore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedCore.
func (in *OpenStackLightspeedCore) DeepCopy() *OpenStackLightspeedCore {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedDefaults) DeepCopyInto(out *OpenStackLightspeedDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedDefaults.
func (in *OpenStackLightspeedDefaults) DeepCopy() *OpenStackLightspeedDefaults {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedList) DeepCopyInto(out *OpenStackLightspeedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackLightspeed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedList.
func (in *OpenStackLightspeedList) DeepCopy() *OpenStackLightspeedList {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackLightspeedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedSpec) DeepCopyInto(out *OpenStackLightspeedSpec) {
	*out = *in
	out.OpenStackLightspeedCore = in.OpenStackLightspeedCore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedSpec.
func (in *OpenStackLightspeedSpec) DeepCopy() *OpenStackLightspeedSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedStatus) DeepCopyInto(out *OpenStackLightspeedStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedStatus.
func (in *OpenStackLightspeedStatus) DeepCopy() *OpenStackLightspeedStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedStatus)
	in.DeepCopyInto(out)
	return out
}
